### PR TITLE
Clarifies documentation of how to use --interleaved

### PR DESCRIPTION
**Pull request by bwlang**
I had some trouble trying to do this sort of thing:
```
bowtie2 --interleaved -x /path/to/bowtie2_index/hg19 <all kind of stuff here -12, -1, -U ...> r1_r2_interleaved.fastq
```
but this works:
```
bowtie2 -x /path/to/bowtie2_index/hg19 --interleaved r1_r2_interleaved.fastq
```
This doc change describes what worked for me.
I did not test tab5/6 files, but they may have the same usage

### CODE REVIEW

**Comment by bwlang** [comment]
Did the build break because of this commit or is it broken for some other reason?

**Comment by dnbh** [comment]
You're missing a semicolon at the end of line 679.

**Comment by bwlang** [comment]
looks like i'm actually going to have to check this code out  - doh!

**Comment by bwlang** [comment]
hmm my local checkout does build ok (macos)
--help looks like this:
```
Bowtie 2 version 2.3.1 by Ben Langmead (langmea@cs.jhu.edu, www.cs.jhu.edu/~langmea)
Usage:
  bowtie2 [options]* -x <bt2-idx> {-1 <m1> -2 <m2> | -U <r> | --interleaved <i>} [-S <sam>]

  <bt2-idx>  Index filename prefix (minus trailing .X.bt2).
             NOTE: Bowtie 1 and Bowtie 2 indexes are not compatible.
  <m1>       Files with #1 mates, paired with files in <m2>.
             Could be gzip'ed (extension: .gz) or bzip2'ed (extension: .bz2).
  <m2>       Files with #2 mates, paired with files in <m1>.
             Could be gzip'ed (extension: .gz) or bzip2'ed (extension: .bz2).
  <r>        Files with unpaired reads.
             Could be gzip'ed (extension: .gz) or bzip2'ed (extension: .bz2).
  <i>        Files with interleaved paired-end FASTQ reads
             Could be gzip'ed (extension: .gz) or bzip2'ed (extension: .bz2).
  <sam>      File for SAM output (default: stdout)

```

not sure why travis is unhappy.
error: use of undeclared identifier 'gzbuffer'

**Comment by dnbh** [comment]
The problem with gzbuffer is that it's dependent on a sufficiently-new zlib. If you a macro protection of ZLIB_VERNUM >= 0x1235 and only apply gzbuffer if available, you should be fine. I think that may have been fixed in downstream versions.

**Pull request merged**
